//! Deterministic dense vector embedding and similarity search system.
//!
//! Provides dense, high-dimensional vector representations of text without
//! external neural network weights or API dependencies, keeping the system
//! fully offline, lightweight, and fast. It relies on deterministic random projection
//! (random indexing) over word tokens, producing unit-length vectors.
//! Cosine similarity is computed via dot products.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::time::{SystemTime, UNIX_EPOCH};

const DEFAULT_DIMENSIONS: usize = 128;

/// A stable, deterministic 64-bit FNV-1a hash.
pub fn fnv1a_hash(s: &str) -> u64 {
    let mut hash = 0xcbf29ce484222325;
    for byte in s.as_bytes() {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}

/// A simple, fast, deterministic PRNG to generate stable projection weights.
struct DeterministicPrng {
    state: u64,
}

impl DeterministicPrng {
    fn new(seed: u64) -> Self {
        Self {
            state: if seed == 0 { 0x123456789abcdef } else { seed },
        }
    }

    fn next_f32(&mut self) -> f32 {
        // Numerical Recipes LCG parameters
        self.state = self.state.wrapping_mul(1664525).wrapping_add(1013904223);
        let bits = (self.state & 0xffffffff) as u32;
        (bits as f32 / u32::MAX as f32) * 2.0 - 1.0
    }
}

/// Helper to tokenize text into lowercase alphanumeric tokens of length >= 2.
pub fn tokenize(text: &str) -> Vec<String> {
    text.split(|c: char| !c.is_alphanumeric())
        .map(|t| t.to_lowercase())
        .filter(|t| t.len() >= 2)
        .collect()
}

/// Deterministically embeds text into a dense vector of specified dimensions.
///
/// Under the hood, this uses random projection (random indexing) of tokenized terms.
/// The resulting vector is L2-normalized to unit length.
pub fn embed(text: &str, dimensions: usize) -> Vec<f32> {
    let tokens = tokenize(text);
    if tokens.is_empty() {
        return vec![0.0; dimensions];
    }

    // Compute Term Frequencies (TF)
    let mut counts = HashMap::new();
    for t in &tokens {
        *counts.entry(t).or_insert(0usize) += 1;
    }

    let mut doc_vector = vec![0.0f32; dimensions];

    for (token, count) in counts {
        let seed = fnv1a_hash(token);
        let mut prng = DeterministicPrng::new(seed);

        // Compute term frequency weight (log-scaled frequency)
        let tf_weight = 1.0 + (count as f32).ln();

        for val_mut in &mut doc_vector {
            // Generate deterministic projection coordinate in [-1, 1]
            let val = prng.next_f32();
            *val_mut += tf_weight * val;
        }
    }

    // Normalize to L2 unit length
    let mut norm_sq = 0.0f32;
    for &val in &doc_vector {
        norm_sq += val * val;
    }
    let norm = norm_sq.sqrt();

    if norm > 1e-9 {
        for val in &mut doc_vector {
            *val /= norm;
        }
    } else {
        doc_vector = vec![0.0; dimensions];
    }

    doc_vector
}

/// Calculates cosine similarity between two dense vectors of the same dimension.
///
/// Since the vectors generated by `embed` are normalized to unit length,
/// cosine similarity is simply their dot product.
pub fn cosine_similarity(a: &[f32], b: &[f32]) -> f32 {
    if a.len() != b.len() || a.is_empty() {
        return 0.0;
    }
    let mut dot = 0.0f32;
    for i in 0..a.len() {
        dot += a[i] * b[i];
    }
    dot
}

/// A single entry in the vector store.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VectorEntry {
    pub id: String,
    pub text: String,
    pub vector: Vec<f32>,
    pub metadata: serde_json::Value,
}

/// Result of a nearest neighbor search.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VectorSearchResult {
    pub entry: VectorEntry,
    pub score: f32,
}

/// A persistent, in-memory vector database.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct VectorStore {
    pub entries: Vec<VectorEntry>,
    pub dimensions: usize,
}

impl VectorStore {
    /// Creates a new vector store with default dimensions (128).
    pub fn new() -> Self {
        Self {
            entries: Vec::new(),
            dimensions: DEFAULT_DIMENSIONS,
        }
    }

    /// Creates a new vector store with specified dimensions.
    pub fn with_dimensions(dimensions: usize) -> Self {
        Self {
            entries: Vec::new(),
            dimensions,
        }
    }

    /// Adds a text block into the store. Returns the ID of the new entry.
    pub fn add(&mut self, id: Option<String>, text: &str, metadata: serde_json::Value) -> String {
        let id = id.unwrap_or_else(|| {
            let now = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map(|d| d.as_secs())
                .unwrap_or(0);
            format!("vec-{now}-{:x}", fnv1a_hash(text) & 0xffff)
        });

        let vector = embed(text, self.dimensions);

        let entry = VectorEntry {
            id: id.clone(),
            text: text.to_string(),
            vector,
            metadata,
        };

        // Remove any existing entry with the same ID
        self.entries.retain(|e| e.id != id);
        self.entries.push(entry);

        id
    }

    /// Retrieve top K nearest neighbors for the query string using cosine similarity.
    pub fn search(&self, query: &str, limit: usize) -> Vec<VectorSearchResult> {
        let q_vec = embed(query, self.dimensions);
        let mut scored: Vec<VectorSearchResult> = self
            .entries
            .iter()
            .map(|entry| {
                let score = cosine_similarity(&q_vec, &entry.vector);
                VectorSearchResult {
                    entry: entry.clone(),
                    score,
                }
            })
            .collect();

        // Sort descending by score. NaN-safe sorting.
        scored.sort_by(|a, b| {
            b.score
                .partial_cmp(&a.score)
                .unwrap_or(std::cmp::Ordering::Equal)
        });

        if limit > 0 {
            scored.into_iter().take(limit).collect()
        } else {
            scored
        }
    }

    /// Save the store to a JSON file.
    pub fn save_to_file(&self, path: impl AsRef<std::path::Path>) -> anyhow::Result<()> {
        let path = path.as_ref();
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let json = serde_json::to_string_pretty(self)?;
        std::fs::write(path, json)?;
        Ok(())
    }

    /// Load the store from a JSON file.
    pub fn load_from_file(path: impl AsRef<std::path::Path>) -> anyhow::Result<Self> {
        let path = path.as_ref();
        if !path.exists() {
            return Ok(Self::new());
        }
        let data = std::fs::read_to_string(path)?;
        let store: Self = serde_json::from_str(&data)?;
        Ok(store)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tokenization() {
        let tokens = tokenize("The quick, brown fox jumps!");
        assert_eq!(tokens, vec!["the", "quick", "brown", "fox", "jumps"]);
    }

    #[test]
    fn test_deterministic_embedding_generation() {
        let text = "Rust is a systems programming language.";
        let vec1 = embed(text, 128);
        let vec2 = embed(text, 128);

        // Check dimension size
        assert_eq!(vec1.len(), 128);
        assert_eq!(vec2.len(), 128);

        // Check determinism (identical input produces identical outputs)
        for i in 0..128 {
            assert!((vec1[i] - vec2[i]).abs() < 1e-6);
        }

        // Check L2 normalization (norm = 1.0)
        let mut sum_sq = 0.0f32;
        for &v in &vec1 {
            sum_sq += v * v;
        }
        assert!((sum_sq.sqrt() - 1.0).abs() < 1e-4);
    }

    #[test]
    fn test_cosine_similarity() {
        let v1 = embed("The quick brown fox jumps over the lazy dog", 128);
        let v2 = embed("The quick brown fox jumps over the lazy dog", 128);
        let v3 = embed("Rust systems programming language safety", 128);

        // Similarity of identical vectors is 1.0
        let sim_self = cosine_similarity(&v1, &v2);
        assert!((sim_self - 1.0).abs() < 1e-4);

        // Similarity of different vectors is lower than 1.0
        let sim_other = cosine_similarity(&v1, &v3);
        assert!(sim_other < 0.8);
    }

    #[test]
    fn test_vector_store_crud_and_persistence() {
        let temp_dir = std::env::temp_dir();
        let path = temp_dir.join("test_vector_store_crud.json");

        let mut store = VectorStore::with_dimensions(128);
        assert_eq!(store.entries.len(), 0);

        // Add entries
        let _id1 = store.add(
            None,
            "First entry about cats",
            serde_json::json!({"tag": "animals"}),
        );
        let id2 = store.add(
            Some("custom-id-2".to_string()),
            "Second entry about rust programming",
            serde_json::json!({"tag": "tech"}),
        );

        assert_eq!(store.entries.len(), 2);
        assert_eq!(id2, "custom-id-2");

        // Overwrite entry with same ID
        store.add(
            Some("custom-id-2".to_string()),
            "Updated second entry about rust programming language",
            serde_json::json!({"tag": "technology"}),
        );
        assert_eq!(store.entries.len(), 2);

        // Save to disk
        store.save_to_file(&path).unwrap();

        // Load from disk
        let loaded_store = VectorStore::load_from_file(&path).unwrap();
        assert_eq!(loaded_store.entries.len(), 2);
        assert_eq!(loaded_store.dimensions, 128);

        // Verify loaded content
        let second_entry = loaded_store
            .entries
            .iter()
            .find(|e| e.id == "custom-id-2")
            .unwrap();
        assert_eq!(
            second_entry.text,
            "Updated second entry about rust programming language"
        );
        assert_eq!(second_entry.metadata["tag"], "technology");

        // Clean up
        let _ = std::fs::remove_file(path);
    }
}
