root ::= prose ;
prose ::= paragraph { ("\n" "\n" paragraph) } ;
paragraph ::= sentence { (" " sentence) } ( "." | "?" | "!" ) ;
sentence ::= word { (" " word) } ;
word ::= letter { letter | digit | "'" | "," | ";" | ":" | "-" | "(" | ")" | "\"" } ;
letter ::= #'[A-Za-z]' ;
digit ::= #'[0-9]' ;