root ::= sentence terminator | sentence " " sentence terminator | sentence " " sentence " " sentence terminator | sentence " " sentence " " sentence " " sentence terminator ;
sentence ::= word | word " " word | word " " word " " word ;
word ::= letter ( letter | digit | "'" | "," | ";" | ":" | "-" | "(" | ")" | "\"" )* ;
letter ::= #'[A-Za-z]' ;
digit ::= #'[0-9]' ;
terminator ::= "." | "?" | "!" ;
